<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcScope.Core\PlcScope.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PlcComm.Slmp">
      <HintPath>..\..\lib\plc-comm\net9.0\PlcComm.Slmp.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="PlcComm.KvHostLink">
      <HintPath>..\..\lib\plc-comm\net9.0\PlcComm.KvHostLink.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="PlcComm.Toyopuc">
      <HintPath>..\..\lib\plc-comm\net9.0\PlcComm.Toyopuc.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
