<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcScope.Core\PlcScope.Core.csproj" />
    <PackageReference Include="PlcComm.Slmp" />
    <PackageReference Include="PlcComm.KvHostLink" />
    <PackageReference Include="PlcComm.Toyopuc" />
  </ItemGroup>

</Project>
