<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="PlcComm.KvHostLink" Version="0.1.7" />
    <PackageVersion Include="PlcComm.Slmp" Version="0.1.11" />
    <PackageVersion Include="PlcComm.Toyopuc" Version="0.1.3" />
    <PackageVersion Include="System.Text.Encoding.CodePages" Version="9.0.4" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
